Repository astrolabsoftware/fink-filters, pull requests merged in 2021-06, with the labels that each got.

#55 Add a new Slack redirection for KN for DWF
  fink_filters/filter_early_kn_candidates/filter.py
Labels: kilonovae, slack

#56 Bump version to 0.2.14
  fink_filters/__init__.py
Labels: release

#57 Bump version to 0.2.15
  fink_filters/__init__.py
  fink_filters/filter_early_kn_candidates/filter.py
Labels: release

#66 Bump to 0.2.16
  fink_filters/__init__.py
Labels: release

#67 Add cross-match with SDSS catalog to filter stars
  fink_filters/filter_early_kn_candidates/filter.py
Labels: kilonovae

#72 Bump to 0.2.17
  fink_filters/__init__.py
Labels: release
