Repository astrolabsoftware/fink-filters, pull requests merged in 2022-04, with the labels that each got.

#109 Switch to fink-utils
  .github/workflows/run_test.yml
  fink_filters/filter_early_kn_candidates/filter.py
  fink_filters/filter_kn_candidates/filter.py
  fink_filters/filter_orphan_grb_candidates/filter.py
  fink_filters/filter_rate_based_kn_candidates/filter.py
  requirements.txt
Labels: cleaning

#111 Move utilities to fink-utils
  .github/workflows/run_test.yml
  fink_filters/__init__.py
  fink_filters/filter_early_kn_candidates/filter.py
  fink_filters/filter_early_sn_candidates/filter.py
  fink_filters/filter_kn_candidates/filter.py
  fink_filters/filter_microlensing_candidates/filter.py
  fink_filters/filter_orphan_grb_candidates/filter.py
  fink_filters/filter_rate_based_kn_candidates/filter.py
  fink_filters/filter_rrlyr/filter.py
  fink_filters/filter_simbad_candidates/filter.py
  fink_filters/filter_sn_candidates/filter.py
  fink_filters/filter_sso_fink_candidates/filter.py
  fink_filters/filter_sso_ztf_candidates/filter.py
  fink_filters/filter_tracklet_candidates/filter.py
  fink_filters/utilities.py
Labels: cleaning

#113 Add a new filter based on Candidate_YSO and Candidate_TTau*
  README.md
  fink_filters/__init__.py
  fink_filters/filter_yso_candidates/__init__.py
  fink_filters/filter_yso_candidates/filter.py
Labels: new filter

#115 Incorrect link to fink classifications in the README
  README.md
Labels: bug, documentation
