Repository astrolabsoftware/fink-filters, pull requests merged in 2024-05, with the labels that each got.

#177 made class modification
  fink_filters/filter_mm_module/filter.py
Labels: bug, multi-messenger

#180 Filter: Dwarf AGN
  datatest/dwarf_agn/dwarf_agn.parquet
  fink_filters/__init__.py
  fink_filters/data/list_dwarfs_AGN_RADEC.parquet
  fink_filters/filter_dwarf_agn/__init__.py
  fink_filters/filter_dwarf_agn/filter.py
Labels: new filter

#183 Check if the environment variables are not empty
  fink_filters/filter_early_kn_candidates/filter.py
  fink_filters/filter_early_sn_candidates/filter.py
  fink_filters/filter_kn_candidates/filter.py
  fink_filters/filter_yso_spicy_candidates/filter.py
Labels: bug
